name: Run CSGO Empire E2E tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          apt update
          apt install libnss3-dev libasound2 libatk-bridge2.0-0 libx11-xcb1 libxcb-dri3-0 libxshmfence1 libgtk-3-0 libgbm1
          npm install
          npx playwright install

      - name: Run Playwright tests
        run: |
          npx playwright test
